# Generated by Django 4.1.3 on 2022-12-08 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('films', '0003_rename_laguage_language_alter_film_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rent', models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 8, 19, 41, 21, 875459))),
                ('actual_return', models.DateTimeField()),
                ('rental_count', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='films.item')),
            ],
        ),
    ]
