# Generated by Django 4.1.3 on 2023-01-11 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rental_count',
        ),
        migrations.AlterField(
            model_name='rent',
            name='actual_return',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 13, 14, 36, 918913)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 13, 14, 36, 918901)),
        ),
    ]
