# Generated by Django 4.1.3 on 2023-01-11 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0005_remove_rent_rental_count_alter_rent_actual_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='client',
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='actual_return',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 17, 21, 53, 303818)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 17, 21, 53, 303807)),
        ),
    ]
