# Generated by Django 4.1.3 on 2023-01-11 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_rent_actual_return_alter_rent_date_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='actual_return',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 18, 6, 56, 126738)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 18, 6, 56, 126726)),
        ),
    ]
