# Generated by Django 4.1.3 on 2023-01-11 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_rent_actual_return_alter_rent_date_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='actual_return',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 20, 31, 31, 303655)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 20, 31, 31, 303642)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rented_item', to='films.item'),
        ),
    ]
