# Generated by Django 4.1.3 on 2023-01-19 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_rent_film_alter_rent_actual_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='actual_return',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 14, 49, 9, 665877)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 14, 49, 9, 665865)),
        ),
    ]
