# Generated by Django 4.1.3 on 2023-01-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_rent_actual_return_alter_rent_date_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='film',
        ),
        migrations.AlterField(
            model_name='rent',
            name='actual_return',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 18, 2, 43, 313952)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_rent',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 18, 2, 43, 313940)),
        ),
    ]
